version: "3.9"

services:
  recommender:
    build: .
    container_name: recommender_service
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    restart: unless-stopped
    networks: 
      - rental-network  

networks:
  rental-network:
    name: rental-network 
    external: true
